# Generated by Django 3.1.5 on 2021-01-26 14:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0003_auto_20210125_0405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Friend', models.ManyToManyField(blank=True, related_name='friend_added', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
