# Generated by Django 3.1.5 on 2021-01-26 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_friend_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='Friend',
            new_name='friends',
        ),
    ]
